// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mcr_service_user.Infrastructure.Data;

namespace mcr_service_user.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20211102070251_V1_initDbUser")]
    partial class V1_initDbUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("mcr_service_user.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherData")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fb678c25-184a-4f88-aca6-750405b0dfc3"),
                            Mail = "phatht@vietinfo.tech",
                            Name = "Huỳnh Tấn Phát",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("f59bcb26-dbbe-4b2f-b699-4d13d90baf27"),
                            Mail = "phat@gmail.com",
                            Name = "Phát",
                            Status = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
