// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mcr_service_webhooks.Infrastructure.Data;

#nullable disable

namespace mcr_service_webhooks.Migrations
{
    [DbContext(typeof(WebHookApiDbContext))]
    partial class WebHookApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("mcr_service_webhooks.Domain.Models.DomainEvent", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActorID")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("mcr_service_webhooks.Domain.Models.WebHook", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT");

                    b.Property<int>("HookEvents")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastTrigger")
                        .HasColumnType("TEXT");

                    b.Property<string>("Secret")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebHookUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("WebHooks");
                });

            modelBuilder.Entity("mcr_service_webhooks.Domain.Models.WebHookHeader", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.Property<long>("WebHookID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("WebHookID");

                    b.ToTable("WebHookHeader");
                });

            modelBuilder.Entity("mcr_service_webhooks.Domain.Models.WebHookRecord", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<int>("HookType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("TEXT");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("WebHookID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("WebHookID");

                    b.ToTable("WebHooksHistory");
                });

            modelBuilder.Entity("mcr_service_webhooks.Domain.Events.WebHookCreated", b =>
                {
                    b.HasBaseType("mcr_service_webhooks.Domain.Models.DomainEvent");

                    b.Property<long>("WebHookId")
                        .HasColumnType("INTEGER");

                    b.ToTable("WebHookCreatedEvent", (string)null);
                });

            modelBuilder.Entity("mcr_service_webhooks.Domain.Events.WebHookRemoved", b =>
                {
                    b.HasBaseType("mcr_service_webhooks.Domain.Models.DomainEvent");

                    b.Property<long>("WebHookId")
                        .HasColumnType("INTEGER");

                    b.ToTable("WebHookRemovedEvent", (string)null);
                });

            modelBuilder.Entity("mcr_service_webhooks.Domain.Events.WebHookUpdated", b =>
                {
                    b.HasBaseType("mcr_service_webhooks.Domain.Models.DomainEvent");

                    b.Property<long>("WebHookId")
                        .HasColumnType("INTEGER");

                    b.ToTable("WebHookUpdatedEvent", (string)null);
                });

            modelBuilder.Entity("mcr_service_webhooks.Domain.Models.WebHookHeader", b =>
                {
                    b.HasOne("mcr_service_webhooks.Domain.Models.WebHook", "WebHook")
                        .WithMany("Headers")
                        .HasForeignKey("WebHookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebHook");
                });

            modelBuilder.Entity("mcr_service_webhooks.Domain.Models.WebHookRecord", b =>
                {
                    b.HasOne("mcr_service_webhooks.Domain.Models.WebHook", "WebHook")
                        .WithMany("Records")
                        .HasForeignKey("WebHookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebHook");
                });

            modelBuilder.Entity("mcr_service_webhooks.Domain.Events.WebHookCreated", b =>
                {
                    b.HasOne("mcr_service_webhooks.Domain.Models.DomainEvent", null)
                        .WithOne()
                        .HasForeignKey("mcr_service_webhooks.Domain.Events.WebHookCreated", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mcr_service_webhooks.Domain.Events.WebHookRemoved", b =>
                {
                    b.HasOne("mcr_service_webhooks.Domain.Models.DomainEvent", null)
                        .WithOne()
                        .HasForeignKey("mcr_service_webhooks.Domain.Events.WebHookRemoved", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mcr_service_webhooks.Domain.Events.WebHookUpdated", b =>
                {
                    b.HasOne("mcr_service_webhooks.Domain.Models.DomainEvent", null)
                        .WithOne()
                        .HasForeignKey("mcr_service_webhooks.Domain.Events.WebHookUpdated", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mcr_service_webhooks.Domain.Models.WebHook", b =>
                {
                    b.Navigation("Headers");

                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
